# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for NeuraBreak — Windows one-folder build.

Usage (from repo root):
    uv run pyinstaller packaging/windows/build.spec --noconfirm

Output:
    dist/NeuraBreak/NeuraBreak.exe   <-- the launcher
    dist/NeuraBreak/                  <-- everything else (DLLs, Qt plugins, model…)

Then run Inno Setup on packaging/windows/installer.iss to produce the .exe
installer that users actually download.

Notes:
  - We use one-folder mode (not one-file) for faster cold-start and easier
    antivirus compatibility. The installer wraps it into a single .exe anyway.
  - UPX is enabled for DLLs but NOT for the main .exe — some AV scanners flag
    UPX-compressed executables incorrectly.
  - Heavy training deps (torch, torchvision, wandb, albumentations) are
    explicitly excluded — the packaged app only needs onnxruntime at inference time.
"""

import os
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files

ROOT = Path(SPECPATH).parent.parent  # repo root, two levels above packaging/windows/

# Data files: model, sound pack, UI assets

datas = []

# Sound pack — always present (generated by tools/generate_sounds.py)
sounds_dir = ROOT / "src" / "neurabreak" / "ui" / "assets" / "sounds"
if sounds_dir.exists():
    datas.append((str(sounds_dir), "neurabreak/ui/assets/sounds"))

# UI assets beyond sounds (icons etc.) when they exist
assets_dir = ROOT / "src" / "neurabreak" / "ui" / "assets"
for child in assets_dir.iterdir():
    if child.is_file():
        datas.append((str(child), "neurabreak/ui/assets"))

# Shared app logo (used for window branding across the UI)
logo_svg = ROOT / "assets" / "logo" / "neurabreak_logo.svg"
if logo_svg.exists():
    datas.append((str(logo_svg), "assets/logo"))

# ONNX model — prefer the fine-tuned one; fall back to placeholder .pt
onnx_model = ROOT / "models" / "neurabreak.onnx"
pt_model_26 = ROOT / "yolo26n.pt"
pt_model_fallback = ROOT / "models" / "yolo26n.pt"

if onnx_model.exists():
    datas.append((str(onnx_model), "models"))
elif pt_model_26.exists():
    datas.append((str(pt_model_26), "."))   # lands in same dir as exe
elif pt_model_fallback.exists():
    datas.append((str(pt_model_fallback), "models"))
else:
    print("WARNING: No model file found at build time — the app will start in stub mode.")

# onnxruntime data files (schema, config JSON, etc.) — dynamic libs are
# handled by pyinstaller-hooks-contrib; we collect the data portion here.
datas += collect_data_files("onnxruntime", include_py_files=False)


hidden = [
    # NeuraBreak sub-packages
    "neurabreak",
    "neurabreak.core",
    "neurabreak.core.config",
    "neurabreak.core.events",
    "neurabreak.core.logging",
    "neurabreak.core.state_machine",
    "neurabreak.core.startup",
    "neurabreak.core.updater",
    "neurabreak.ai",
    "neurabreak.ai.camera",
    "neurabreak.ai.detection_service",
    "neurabreak.ai.engine",
    "neurabreak.ai.postprocessor",
    "neurabreak.data",
    "neurabreak.data.database",
    "neurabreak.data.journal",
    "neurabreak.data.models",
    "neurabreak.notifications",
    "neurabreak.notifications.manager",
    "neurabreak.notifications.audio",
    "neurabreak.notifications.escalation",
    "neurabreak.notifications.platforms",
    "neurabreak.notifications.platforms.windows",
    "neurabreak.notifications.platforms.linux",
    "neurabreak.notifications.platforms.macos",
    "neurabreak.plugins",
    "neurabreak.plugins.base",
    "neurabreak.plugins.loader",
    "neurabreak.ui",
    "neurabreak.ui.app",
    "neurabreak.ui.tray",
    "neurabreak.ui.break_screen",
    "neurabreak.ui.dashboard",
    "neurabreak.ui.preview",
    "neurabreak.ui.settings",

    # Core dependencies
    "structlog",
    "pydantic",
    "pydantic.v1",
    "pydantic_core",
    "pydantic_settings",
    "transitions",
    "transitions.extensions",

    # PySide6 / Qt — platform + image plugins PyInstaller often misses
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtNetwork",

    # ONNX Runtime
    "onnxruntime",
    "onnxruntime.capi",
    "onnxruntime.capi._pybind_state",

    # OpenCV
    "cv2",

    # Audio
    "sounddevice",
    "soundfile",
    "cffi",
    "_cffi_backend",

    # Data layer
    "sqlalchemy",
    "sqlalchemy.dialects.sqlite",
    "sqlalchemy.orm",
    "sqlalchemy.pool",

    # Notifications 
    "plyer",
    "plyer.platforms",
    "plyer.platforms.win.notification",
    "windows_toasts",

    # System / misc
    "psutil",
    "psutil._pswindows",
    "pynput",
    "pynput.keyboard",
    "pynput.mouse",
    "winreg",
    "tomllib",
    "tomli",  # tomllib backport for Python <3.11 (not needed but harmless)
    "urllib.request",
    "urllib.error",
    "json",
    "threading",
    "queue",
    "ctypes",
    "ctypes.wintypes",
]

# Excluded modules: training stack + things we definitely don't need at runtime

excluded = [
    "torch",
    "torchvision",
    "torchaudio",
    "ultralytics",
    "wandb",
    "albumentations",
    "matplotlib",
    "IPython",
    "jupyter",
    "notebook",
    "roboflow",
    "tkinter",
    "unittest",
    "xmlrpc",
    "pydoc",
    "doctest",
    "test",
    "tests",
]

# Version info file (embedded in .exe Properties → Details tab)

_version_file = str(ROOT / "packaging" / "windows" / "version_info.txt")
_version_file = _version_file if Path(_version_file).exists() else None

# Icon – fall back gracefully if not yet generated

_icon_path = ROOT / "packaging" / "windows" / "icon.ico"
_icon = str(_icon_path) if _icon_path.exists() else None

# Analysis

a = Analysis(
    [str(ROOT / "src" / "neurabreak" / "__main__.py")],
    pathex=[str(ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hidden,
    hookspath=[str(ROOT / "packaging" / "windows" / "hooks")],
    hooksconfig={
        "matplotlib": {"backends": []},  # keep matplotlib out if it snuck in
    },
    runtime_hooks=[
        str(ROOT / "packaging" / "windows" / "hooks" / "rthook_pyside6.py"),
    ] if (ROOT / "packaging" / "windows" / "hooks" / "rthook_pyside6.py").exists() else [],
    excludes=excluded,
    noarchive=False,
    optimize=1,  # .pyc optimization level (strip docstrings = level 2, but 1 is safer)
)

# Remove duplicate files that sometimes appear with PySide6 / onnxruntime
seen = set()
unique_binaries = []
for name, path, kind in a.binaries:
    key = name.lower()
    if key not in seen:
        seen.add(key)
        unique_binaries.append((name, path, kind))
a.binaries = unique_binaries

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="NeuraBreak",
    debug=False,

    # Don't UPX the main .exe — some AV products flag it as suspicious.
    # DLLs in COLLECT below are still UPX'd.
    upx=False,
    upx_exclude=["NeuraBreak.exe"],

    console=False,       # windowless — it's a tray app, no terminal
    bootloader_ignore_signals=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,    # same arch as the build machine (x64 on modern Windows)
    codesign_identity=None,
    entitlements_file=None,

    # Windows version resource (shows in File Explorer → Properties → Details)
    version=_version_file,

    # Application icon
    icon=_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=["NeuraBreak.exe", "python*.dll", "vcruntime*.dll"],
    name="NeuraBreak",
)
